### ISSUE TITLE
Google Colab for Examples

### ISSUE THREAD

**Issue by bionboy** [PeterWang512/GANSketching#2]
_Not exactly an issue._

I created a Google Colab Notebook that sets up the repo and calls the example commands in the readme.
I did this because of issues I was having on my local setup. Hopefully this could be added to give an easier quick start for those interested in the project.

[Colab Link](https://colab.research.google.com/drive/1AY6hFr_PrnzDFjXFgebjaM-3brtBucX9?usp=sharing)

**Comment by PeterWang512** [comment]
Thanks for making this!
